### Zadanie 0.
Utwórz skrypt definiujący poniższe zmienne:

a = [1, 2, 3, 4, ..., 100] (wektor złożony z liczb całkowitych od 1 do 100)

b = [1, 3, 5, 7, ..., 99] (wektor złożony z liczb całkowitych nieparzystych od 1 do 99) 

c = [-1.00 * π, -0.99 * π, ..., -0.01 * π, 0, 0.01 * π, ..., 0.99 * π, 1.00 * π]

d = [-1.00 * π, -0.99 * π, ..., -0.01 * π, 0.01 * π, ..., 0.99 * π, 1.00 * π]

e = [e1, e2, ..., e100], gdzie ei = sin(i), jeśli sin(i) > 0, lub ei = 0 w przeciwnym przypadku

A = macierz rozmiaru 10 x 10 zawierająca liczby całkowite od 1 do 100: w pierwszym wierszu od lewej 1, 2, ..., w drugim wierszu od lewej 11, 12, .., itd. (wskazówka: użyć polecenia reshape) 

B = macierz trójdiagonalna rozmiaru 100 x 100 mająca na głównej przekątnej liczby całkowite od 1 do 100, a poniżej i powyżej głównej przekątnej liczby od 99 do 1

C = macierz trójkątna górna wypełniona jedynkami (łącznie z główną przekątną)

D = macierz rozmiaru 2 x 100, w której pierwszy wiersz zawiera elementy d1i = 1 + 2 + ... + i, a
drugi wiersz zawiera elementy d2i = i!

E = macierz rozmiaru 100 x 100 mająca 1 w pozycji (i, j), jeśli i dzieli j, lub 0 w przeciwnym przypadku.

In [7]:
a = 1:100;
b = 1:2:99;
c = -pi : 0.01*pi : pi;
c = round(c * 10 ^ 6)/10 ^ 6;
d = c(c~=0);
e = max(0, sin(1 : 100));

In [8]:
A = transpose(reshape(a, [10,10]));
B = diag(1:100) + diag(99:-1:1, 1) + diag(99:-1:1, -1);
C = triu(ones(10));
D = [cumsum(1:100);cumprod(1:100)];

E = ones(100);
for i = 1:100
    for j = 1:100
        E(i, j) = mod(j, i) == 0;
    endfor
endfor

### Zadanie 1.
a) Niech x, y, w będą wektorami kolumnowymi ustalonej długości d. Policz:
- długość wektora x,
- średnią ważoną wektora x z wagami w,
- odległość euklidesową między wektorami x i y,
- iloczyn skalarny wektorów x i y.
Obliczenia przeprowadź dla losowo wygenerowanych wektorów x, y, w (dla d = 100).

In [9]:
d = 100;
x = rand(d, 1);
y = rand(d, 1);
w = rand(d, 1);

x_len = sqrt(dot(x, x))
xw = dot(x, w) / sum(w)
xy_dist = sqrt(dot(x-y, x-y))
xy_dot = dot(x, y)

x_len =  5.5268
xw =  0.48375
xy_dist =  4.0664
xy_dot =  24.196


b) Niech X będzie macierzą ustalonego rozmiaru d x N zawierającą N wektorów kolumnowych długości d. Niech y i w będą wektorami kolumnowymi długości d. Policz
- długości kolejnych wektorów z macierzy X (wyznacz wektor długości N zawierający te długości),
- średnią ważoną kolejnych wektorów z macierzy X z wagami w (wyznacz wektor długości N zawierający te średnie),
- odległości euklidesowe między kolejnymi wektorami z macierzy X i wektorem y (wyznacz wektor długości N zawierający te odległości),
- iloczyny skalarne kolejnych wektorów z macierzy X i wektora y (wyznacz wektor długości N zawierający te iloczyny).
Obliczenia przeprowadź dla losowo wygenerowanej macierzy X i losowo wygenerowanych wektorów y i w (dla d = 100 i N = 1000).

In [10]:
d = 100;
N = 1000;

X = rand(d, N);
y = rand(d, 1);
w = rand(d, 1);

X_each_len = sqrt(dot(X, X));
X_each_mean = sum(X .* w) ./ sum(w);
Xy_dist = sqrt(sum((X.-y).**2));
Xy_dot = sum(X.*y);

### Zadanie 2.
Napisz funkcję, która dla danych macierzy X i Y ustalonego rozmiaru d x N i d x M odpowiednio, zawierających N i M wektorów kolumnowych długości d, wyznacza macierz odległości euklidesowych między wektorami tych macierzy, tzn. macierz D rozmiaru N x M, gdzie D(i, j) to odległości między i-tym wektorem z macierzy X i j-tym wektorem z macierzy Y. Oblicz czas działania napisanej funkcji dla losowo wygenerowanych macierzy X i Y dla d = 100 i N = M = 1 000 oraz dla d = 100, N = 10 000 i M = 1 000.

In [5]:
function [dists] = calc_dists(X, Y)
    dists = sqrt((-2 .* X' * Y) .+ (sum(X.**2)') .+ (sum(Y.**2)));
end

In [6]:
d = 100;
N = M = 1000;

X = rand(d, N);
Y = rand(d, M);

tic;
D = calc_dists(X, Y);
toc

N = 10000;

X = rand(d, N);
Y = rand(d, M);

tic;
D = calc_dists(X, Y);
toc

Elapsed time is 0.0236959 seconds.
Elapsed time is 0.168261 seconds.


### Zadanie 3.
Napisz funkcję, która dla danych macierzy X i Y ustalonego rozmiaru d x N i d x M odpowiednio, zawierających N i M wektorów kolumnowych długości d, wyznacza dla każdego wektora z macierzy X najbliższego sąsiada spośród wektorów z macierzy Y, tzn. zwraca wektor h rozmiaru 1 x N, gdzie h(i) to numer wektora z macierzy Y będącego najbliższym sąsiadem i-tego wektora z macierzy X. Napisz też wersję tej funkcji, która wyznacza k najbliższych sąsiadów, tzn. zwraca macierz H rozmiaru k x N, gdzie H(i, j) to numer wektora z macierzy Y będącego i-tym najbliższym sąsiadem j-tego wektora z macierzy X (czyli h(j) = H(1, j)).

In [9]:
function [nearest_vector] = find_nearest_vector(X, Y)
    dists = calc_dists(X, Y);
    [M, I] = min(dists);
    nearest_vector = I;
end

In [14]:
function [nearest_k_vector] = find_k_nearest_vectors(k, X, Y)
    dists = calc_dists(X, Y);
    [S, I] = sort(dists);
    nearest_k_vector = I(1:k, :);
end

In [15]:
N = M = 5;
d = 3;

X = rand(d, N)
Y = rand(d, M)
nearest = find_nearest_vector(X, Y)
k_nearest = find_k_nearest_vectors(3, X, Y)

X =

   0.744953   0.267229   0.039687   0.318376   0.877032
   0.916590   0.972444   0.745530   0.856910   0.690580
   0.364216   0.531060   0.201881   0.264682   0.195282

Y =

   0.26082   0.17798   0.62785   0.53209   0.37297
   0.22481   0.62926   0.32814   0.83632   0.83290
   0.90471   0.13191   0.23567   0.86966   0.14402

nearest_n =

   2   3   5   2   4

k_nearest =

   2   3   5   2   4
   4   4   4   1   3
   3   2   1   4   2



### Zadanie 4.
Utwórz skrypt generujący losowe sudoku, tzn. macierz M rozmiaru 9x9 zawierającą liczby 1, 2, ..., 9, taką, że w każdym wierszu każda z liczb występuje dokładnie jeden raz, w każdej kolumnie każda z liczb występuje dokładnie jeden raz oraz w każdej klatce 3x3, powstałej przez podział macierzy M dwoma liniami pionowymi i dwoma liniami poziomymi, każda z liczb występuje dokładnie jeden raz.

In [99]:
function [sud] = generate(n)
    sud = zeros(n)
    for i = 1:n
        x = randperm(n);
        while !all(all(x .- sud(1:i-1, :)))
            x = randperm(n);
        endwhile
        sud(i, :) = x;
    endfor
end

generate(9)


sud =

   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0

ans =

   9   7   2   1   6   5   3   4   8
   4   1   6   3   5   2   8   7   9
   1   9   5   8   2   6   4   3   7
   5   6   8   4   7   9   1   2   3
   3   4   9   6   1   7   5   8   2
   6   5   4   7   3   8   2   9   1
   7   8   3   2   9   4   6   1   5
   8   2   1   9   4   3   7   5   6
   2   3   7   5   8   1   9   6   4



In [193]:
function [sud] = generate(n)
    flag = true;
    while flag
        try
            flag = false;
            pos = ones(n, n, n);
            sud = zeros(n);
            for i = 1:n
                for j = 1:n
                    [a, p] = find(pos(i, j, :)); % find all possible numbers in pos i,j
                    x = p(randi(1:length(p)));
                    sud(i, j) = x;

                    % update array of possible
                    for k = 1:n
                        pos(i, k, x) = 0;
                        pos(k, j, x) = 0;
                    endfor
                    i1 = i;
                    while mod(i1, 3) != 0 || i1 == i
                        j1 = j;
                        while mod(j1, 3) != 0 || j1 == j
                            pos(i1, j1, x) = 0;
                            j1 += 1;
                        endwhile
                        i1 += 1;
                    endwhile
                endfor
            endfor
        catch
            flag = true;
        end
    endwhile
end

generate(9)

% a = [1 4]
% a = a(randi(1:length(a)))

In [200]:
for i = 0:8
    3*mod(i, 3) + fix(i/3)
endfor

ans = 0
ans =  3
ans =  6
ans =  1
ans =  4
ans =  7
ans =  2
ans =  5
ans =  8


### Zadanie 5.
Zapoznaj się z paradoksem Monty’ego Halla (który był podstawą teleturniejów telewizyjnych "Let’s make a deal", w polskiej wersji "Idź na całość"). Napisz skrypt symulujący taki teleturniej. Przeprowadź minimum 10000 prób i oszacuj prawdopodobieństwo wygranej dla strategii pozostawania przy swoim wyborze oraz dla strategii zmiany wyboru.

In [1]:
wins_stay = 0;
wins_change = 0;
N = 10000;

for i = 1:N
    w = randi(3);
    g1 = randi(3);
    
    wins_stay += w == g1;
    wins_change += w != g1;
endfor
wins_stay/=N
wins_change/=N

wins_stay =  0.32810
wins_change =  0.67190
