In [1]:
import numpy as np
from ES import ES

# Zadanie 1.
a) Zaimplementuj omawiane na wykładzie strategie ewolucyjne ES(μ + λ) i ES(μ, λ).
Wskazówka: Algorytmy można zaimplementować w dowolnym języku programowania, ale ze względu na wygodę i wydajność obliczeń (głównie związanych z operacjami wektorowo-macierzowymi i losowaniem danych z rozkładu normalnego) radziłbym używać środowisk dedykowanych do obliczeń wektorowo- macierzowych, m.in. Matlab, Octave lub Python z biblioteką Numpy.

b) Zapoznaj się z popularnymi benchmarkami dla optymalizacji globalnej (http://www-optima.amp.i.kyoto-u.ac.jp/member/student/hedar/Hedar_files/TestGO.htm), zarówno problemami optymalizacji bez ograniczeń jak i z ograniczeniami. Wybierz 5 benchmarków bez ograniczeń i użyj zaimplementowanych algorytmów do ich rozwiązywania (wśród wybranych benchmarków powinna znaleźć się co najmniej jedna z następujących funkcji: Griewank Function, Rastrigin Function, Schwefel Function). Dokładnie przeanalizuj działanie algorytmu i otrzymane wyniki. Sprawdź różne ustawienia algorytmu.

#### Used benchmarks:
- Sum squares
- Beale function
- Rosenbrock function
- Rastrigin function
- Griewank function

### Sum squares function
##### $f(x) = \sum_{i=1}^n{ix_i^2}$

In [2]:
def sum_squares(population):
    return np.array(list(map(lambda ind: ind[0]**2 * np.arange(1, len(ind[0])+1), 
                             population))).sum(axis=1)

In [3]:
dims = 3

lr = 0.1
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-10, 10), dims=3, population_size=1000, offspring_size=500, 
        parent_choice_method='random', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=sum_squares, max_iters=1000)

In [4]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 0.2753,	mean: 136.4610,	max: 245.2395
iter: 50, min: 0.0050,	mean: 0.7816,	max: 1.2923
iter: 100, min: 0.0044,	mean: 0.4943,	max: 0.7810
iter: 150, min: 0.0044,	mean: 0.3985,	max: 0.6211
iter: 200, min: 0.0044,	mean: 0.3484,	max: 0.5426
iter: 250, min: 0.0044,	mean: 0.3083,	max: 0.4827
iter: 300, min: 0.0044,	mean: 0.2782,	max: 0.4403
iter: 350, min: 0.0044,	mean: 0.2552,	max: 0.4014
iter: 400, min: 0.0044,	mean: 0.2399,	max: 0.3773
iter: 450, min: 0.0044,	mean: 0.2246,	max: 0.3536
iter: 500, min: 0.0044,	mean: 0.2120,	max: 0.3320
iter: 550, min: 0.0044,	mean: 0.2020,	max: 0.3168
iter: 600, min: 0.0044,	mean: 0.1929,	max: 0.3019
iter: 650, min: 0.0044,	mean: 0.1861,	max: 0.2932
iter: 700, min: 0.0044,	mean: 0.1771,	max: 0.2801
iter: 750, min: 0.0044,	mean: 0.1713,	max: 0.2703
iter: 800, min: 0.0044,	mean: 0.1642,	max: 0.2599
iter: 850, min: 0.0044,	mean: 0.1585,	max: 0.2518
iter: 900, min: 0.0044,	mean: 0.1529,	max: 0.2443
iter: 950, min: 0.0044,	mean: 0.1481,	max: 0.2370

(array([[-0.01416125,  0.02697549, -0.03041161],
        [ 1.82364766,  0.70349555,  1.67746035]]), 0.0044304929123652375)

#### optimum = 0 at (0, ..., 0)

### Beale Function
##### $f(x) = (1.5 - x_1 + x_1*x_2)^2 + (2.25 - x_1 + x_1*x_2^2)^2 + (2.625 - x_1 + x_1*x_2^3)^2$

In [5]:
def beale(population):
    return np.array([(1.5 - ind[0][0] + ind[0][0]*ind[0][1])**2 + \
                     (2.25 - ind[0][0] + ind[0][0]*ind[0][1]**2)**2 + \
                     (2.625 - ind[0][0] + ind[0][0]*ind[0][1]**3)**2
                     for ind in population])

In [6]:
dims = 2

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-4.5, 4.5), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='random', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=beale, max_iters=1000)

In [7]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 0.0006,	mean: 339.1181,	max: 2741.4159
iter: 50, min: 0.0000,	mean: 0.0318,	max: 0.0619
iter: 100, min: 0.0000,	mean: 0.0166,	max: 0.0300
iter: 150, min: 0.0000,	mean: 0.0114,	max: 0.0208
iter: 200, min: 0.0000,	mean: 0.0089,	max: 0.0164
iter: 250, min: 0.0000,	mean: 0.0071,	max: 0.0129
iter: 300, min: 0.0000,	mean: 0.0062,	max: 0.0111
iter: 350, min: 0.0000,	mean: 0.0054,	max: 0.0098
iter: 400, min: 0.0000,	mean: 0.0048,	max: 0.0087
iter: 450, min: 0.0000,	mean: 0.0043,	max: 0.0079
iter: 500, min: 0.0000,	mean: 0.0039,	max: 0.0071
iter: 550, min: 0.0000,	mean: 0.0035,	max: 0.0064
iter: 600, min: 0.0000,	mean: 0.0032,	max: 0.0058
iter: 650, min: 0.0000,	mean: 0.0030,	max: 0.0054
iter: 700, min: 0.0000,	mean: 0.0027,	max: 0.0049
iter: 750, min: 0.0000,	mean: 0.0026,	max: 0.0046
iter: 800, min: 0.0000,	mean: 0.0024,	max: 0.0044
iter: 850, min: 0.0000,	mean: 0.0022,	max: 0.0040
iter: 900, min: 0.0000,	mean: 0.0021,	max: 0.0037
iter: 950, min: 0.0000,	mean: 0.0020,	max: 0.003

(array([[3.00023995, 0.49976324],
        [0.81868102, 0.53947066]]), 2.0330172933510365e-06)

#### optimum = 0 at (3, 0.5)

### Rosenbrock Function
##### $f(x) = \sum_{i=1}^{N-1}[100 * (x_{i}^2 - x_{i+1})^2 + (1 - x_i)^2]$

In [8]:
def rosenbrock(population):
    return np.array([(100*(ind[:-1]**2 - ind[1:])**2 + (ind[:-1] - 1)**2).sum() 
                     for ind in population])

In [9]:
dims = 2

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-5, 10), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='random', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=rosenbrock, max_iters=1000)

In [10]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 10.5160,	mean: 78781.2723,	max: 298497.6888
iter: 50, min: 0.0665,	mean: 9.5749,	max: 17.0353
iter: 100, min: 0.0549,	mean: 5.2134,	max: 9.4830
iter: 150, min: 0.0549,	mean: 3.7915,	max: 6.8062
iter: 200, min: 0.0549,	mean: 2.9724,	max: 5.4602
iter: 250, min: 0.0549,	mean: 2.4041,	max: 4.4381
iter: 300, min: 0.0549,	mean: 2.0306,	max: 3.7585
iter: 350, min: 0.0549,	mean: 1.7578,	max: 3.3145
iter: 400, min: 0.0549,	mean: 1.5294,	max: 2.9017
iter: 450, min: 0.0432,	mean: 1.3098,	max: 2.5115
iter: 500, min: 0.0432,	mean: 1.1897,	max: 2.2511
iter: 550, min: 0.0432,	mean: 1.0876,	max: 2.0007
iter: 600, min: 0.0203,	mean: 0.9969,	max: 1.8079
iter: 650, min: 0.0203,	mean: 0.9226,	max: 1.6704
iter: 700, min: 0.0203,	mean: 0.8586,	max: 1.5449
iter: 750, min: 0.0203,	mean: 0.7973,	max: 1.4191
iter: 800, min: 0.0203,	mean: 0.7465,	max: 1.3449
iter: 850, min: 0.0203,	mean: 0.7040,	max: 1.2655
iter: 900, min: 0.0203,	mean: 0.6709,	max: 1.2043
iter: 950, min: 0.0203,	mean: 0.6358,	max:

(array([[0.95706187, 0.87114008],
        [0.91259177, 0.7562615 ]]), 0.020276360620034396)

#### optimum = 0 at (1, ..., 1)

### Rastrigin Function
##### $f(x) = 10*N + \sum_{i=1}^N[{x_i^2 - 10*\cos(2 \pi * x_i)}]$

In [11]:
def rastrigin(population):
    dims = population.shape[-1]
    return 10*dims + np.array([(ind[0]**2 - 10 * np.cos(2*np.pi * ind[0])).sum() 
                               for ind in population])

In [12]:
dims = 2

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-5.12, 5.12), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='random', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=rastrigin, max_iters=1000)

In [13]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 1.5322,	mean: 28.8114,	max: 43.3952
iter: 50, min: 0.0716,	mean: 4.5659,	max: 6.9633
iter: 100, min: 0.0716,	mean: 3.0529,	max: 4.5823
iter: 150, min: 0.0716,	mean: 2.4957,	max: 3.6798
iter: 200, min: 0.0183,	mean: 2.1697,	max: 3.1063
iter: 250, min: 0.0183,	mean: 1.9713,	max: 2.7716
iter: 300, min: 0.0183,	mean: 1.8179,	max: 2.5607
iter: 350, min: 0.0183,	mean: 1.6880,	max: 2.3708
iter: 400, min: 0.0032,	mean: 1.5825,	max: 2.2322
iter: 450, min: 0.0032,	mean: 1.5096,	max: 2.1323
iter: 500, min: 0.0032,	mean: 1.4133,	max: 2.0382
iter: 550, min: 0.0032,	mean: 1.3327,	max: 1.9426
iter: 600, min: 0.0032,	mean: 1.2576,	max: 1.8196
iter: 650, min: 0.0032,	mean: 1.2046,	max: 1.7297
iter: 700, min: 0.0032,	mean: 1.1575,	max: 1.6480
iter: 750, min: 0.0032,	mean: 1.1221,	max: 1.5865
iter: 800, min: 0.0032,	mean: 1.0802,	max: 1.5239
iter: 850, min: 0.0032,	mean: 1.0475,	max: 1.4681
iter: 900, min: 0.0032,	mean: 1.0023,	max: 1.4097
iter: 950, min: 0.0032,	mean: 0.9703,	max: 1.3778


(array([[ 0.00307666, -0.00260417],
        [ 0.82067631,  0.96910184]]), 0.00322329809511146)

#### optimum = 0 at (0, ..., 0)

### Griewank Function
##### $f(x) = 1 + \frac{1}{4000}\sum_{i=1}^Nx_i^2 - \prod_{i=1}^N\cos(\frac{x_i}{\sqrt i})$

In [14]:
def griewank(population):
    dims = population.shape[-1]
    return 1 + 1/4000*np.array([(ind[0]**2).sum() for ind in population]) -\
        np.prod([np.cos(ind[0] / np.sqrt([i+1 for i in range(dims)])) for ind in population])

In [15]:
dims = 2

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-600, 600), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='random', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=griewank, max_iters=1000)

In [16]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 1.0365,	mean: 39.9646,	max: 77.4934
iter: 50, min: 1.0153,	mean: 1.0185,	max: 1.0194
iter: 100, min: 1.0129,	mean: 1.0151,	max: 1.0156
iter: 150, min: 1.0127,	mean: 1.0140,	max: 1.0144
iter: 200, min: 1.0127,	mean: 1.0135,	max: 1.0138
iter: 250, min: 1.0127,	mean: 1.0133,	max: 1.0135
iter: 300, min: 1.0127,	mean: 1.0132,	max: 1.0134
iter: 350, min: 1.0127,	mean: 1.0131,	max: 1.0133
iter: 400, min: 1.0127,	mean: 1.0131,	max: 1.0132
iter: 450, min: 1.0127,	mean: 1.0131,	max: 1.0132
iter: 500, min: 1.0127,	mean: 1.0130,	max: 1.0131
iter: 550, min: 1.0127,	mean: 1.0130,	max: 1.0131
iter: 600, min: 1.0127,	mean: 1.0130,	max: 1.0131
iter: 650, min: 1.0127,	mean: 1.0130,	max: 1.0130
iter: 700, min: 1.0127,	mean: 1.0129,	max: 1.0130
iter: 750, min: 1.0127,	mean: 1.0129,	max: 1.0130
iter: 800, min: 1.0127,	mean: 1.0129,	max: 1.0130
iter: 850, min: 1.0127,	mean: 1.0129,	max: 1.0130
iter: 900, min: 1.0127,	mean: 1.0129,	max: 1.0130
iter: 950, min: 1.0127,	mean: 1.0129,	max: 1.0130


(array([[7.1242794 , 0.05027018],
        [1.27523807, 1.34700032]]), 1.0126894710304037)

#### optimum = 0 at (0, ..., 0)