In [1]:
import numpy as np
from ES import ES

# Zadanie 1.
a) Zaimplementuj omawiane na wykładzie strategie ewolucyjne ES(μ + λ) i ES(μ, λ).
Wskazówka: Algorytmy można zaimplementować w dowolnym języku programowania, ale ze względu na wygodę i wydajność obliczeń (głównie związanych z operacjami wektorowo-macierzowymi i losowaniem danych z rozkładu normalnego) radziłbym używać środowisk dedykowanych do obliczeń wektorowo- macierzowych, m.in. Matlab, Octave lub Python z biblioteką Numpy.

b) Zapoznaj się z popularnymi benchmarkami dla optymalizacji globalnej (http://www-optima.amp.i.kyoto-u.ac.jp/member/student/hedar/Hedar_files/TestGO.htm), zarówno problemami optymalizacji bez ograniczeń jak i z ograniczeniami. Wybierz 5 benchmarków bez ograniczeń i użyj zaimplementowanych algorytmów do ich rozwiązywania (wśród wybranych benchmarków powinna znaleźć się co najmniej jedna z następujących funkcji: Griewank Function, Rastrigin Function, Schwefel Function). Dokładnie przeanalizuj działanie algorytmu i otrzymane wyniki. Sprawdź różne ustawienia algorytmu.

#### Used benchmarks:
- Sum squares
- Beale function
- Rosenbrock function
- Rastrigin function
- Griewank function

### Sum squares function
##### $f(x) = \sum_{i=1}^n{ix_i^2}$

In [2]:
def sum_squares(population):
    return np.array(list(map(lambda ind: ind[0]**2 * np.arange(1, len(ind[0])+1), 
                             population))).sum(axis=1)

In [3]:
dims = 3

lr = 0.1
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

In [4]:
es = ES(domain=(-10, 10), dims=3, population_size=1000, offspring_size=500, 
        parent_choice_method='random', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=sum_squares, max_iters=1000)

es.run(verbose=True, with_tqdm=False)

iter: 0, min: 1.3273,	mean: 135.5529,	max: 244.9116
iter: 50, min: 0.0438,	mean: 0.8838,	max: 1.4160
iter: 100, min: 0.0204,	mean: 0.5829,	max: 0.9240
iter: 150, min: 0.0204,	mean: 0.4709,	max: 0.7318
iter: 200, min: 0.0179,	mean: 0.4012,	max: 0.6303
iter: 250, min: 0.0127,	mean: 0.3479,	max: 0.5484
iter: 300, min: 0.0127,	mean: 0.3133,	max: 0.4952
iter: 350, min: 0.0067,	mean: 0.2830,	max: 0.4508
iter: 400, min: 0.0067,	mean: 0.2588,	max: 0.4136
iter: 450, min: 0.0067,	mean: 0.2418,	max: 0.3823
iter: 500, min: 0.0067,	mean: 0.2263,	max: 0.3568
iter: 550, min: 0.0067,	mean: 0.2146,	max: 0.3393
iter: 600, min: 0.0067,	mean: 0.2016,	max: 0.3190
iter: 650, min: 0.0067,	mean: 0.1919,	max: 0.3006
iter: 700, min: 0.0041,	mean: 0.1848,	max: 0.2885
iter: 750, min: 0.0041,	mean: 0.1794,	max: 0.2780
iter: 800, min: 0.0041,	mean: 0.1738,	max: 0.2698
iter: 850, min: 0.0041,	mean: 0.1677,	max: 0.2612
iter: 900, min: 0.0041,	mean: 0.1628,	max: 0.2534
iter: 950, min: 0.0041,	mean: 0.1579,	max: 0.2480

(array([[-0.00337063,  0.00741049,  0.0361989 ],
        [ 0.94683764,  1.62142016,  1.74908351]]), 0.004052273401970602)

In [5]:
es = ES(domain=(-10, 10), dims=3, population_size=1000, offspring_size=500, 
        parent_choice_method='roulette', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=sum_squares, max_iters=1000)

es.run(verbose=True, with_tqdm=False)

iter: 0, min: 4.6504,	mean: 152.4737,	max: 264.9549
iter: 50, min: 0.0113,	mean: 1.0758,	max: 1.7198
iter: 100, min: 0.0113,	mean: 0.5790,	max: 0.9312
iter: 150, min: 0.0113,	mean: 0.4314,	max: 0.7040
iter: 200, min: 0.0113,	mean: 0.3497,	max: 0.5677
iter: 250, min: 0.0113,	mean: 0.3006,	max: 0.4781
iter: 300, min: 0.0050,	mean: 0.2642,	max: 0.4164
iter: 350, min: 0.0014,	mean: 0.2389,	max: 0.3785
iter: 400, min: 0.0014,	mean: 0.2190,	max: 0.3473
iter: 450, min: 0.0014,	mean: 0.2030,	max: 0.3240
iter: 500, min: 0.0014,	mean: 0.1956,	max: 0.3137
iter: 550, min: 0.0014,	mean: 0.1867,	max: 0.2968
iter: 600, min: 0.0014,	mean: 0.1786,	max: 0.2830
iter: 650, min: 0.0014,	mean: 0.1722,	max: 0.2736
iter: 700, min: 0.0014,	mean: 0.1661,	max: 0.2627
iter: 750, min: 0.0014,	mean: 0.1602,	max: 0.2552
iter: 800, min: 0.0014,	mean: 0.1547,	max: 0.2437
iter: 850, min: 0.0014,	mean: 0.1501,	max: 0.2348
iter: 900, min: 0.0014,	mean: 0.1467,	max: 0.2290
iter: 950, min: 0.0014,	mean: 0.1437,	max: 0.2228

(array([[-0.01822478,  0.0200264 , -0.0101974 ],
        [ 1.4697304 ,  0.80421091,  0.94107027]]), 0.0014462167183425063)

#### optimum = 0 at (0, ..., 0)

### Beale Function
##### $f(x) = (1.5 - x_1 + x_1*x_2)^2 + (2.25 - x_1 + x_1*x_2^2)^2 + (2.625 - x_1 + x_1*x_2^3)^2$

In [6]:
def beale(population):
    return np.array([(1.5 - ind[0][0] + ind[0][0]*ind[0][1])**2 + \
                     (2.25 - ind[0][0] + ind[0][0]*ind[0][1]**2)**2 + \
                     (2.625 - ind[0][0] + ind[0][0]*ind[0][1]**3)**2
                     for ind in population])

In [7]:
dims = 2

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

In [8]:
es = ES(domain=(-4.5, 4.5), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='roulette', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=beale, max_iters=1000)

es.run(verbose=True, with_tqdm=False)

iter: 0, min: 0.0467,	mean: 2403.4320,	max: 14648.3022
iter: 50, min: 0.0000,	mean: 0.0447,	max: 0.0879
iter: 100, min: 0.0000,	mean: 0.0220,	max: 0.0411
iter: 150, min: 0.0000,	mean: 0.0161,	max: 0.0292
iter: 200, min: 0.0000,	mean: 0.0127,	max: 0.0228
iter: 250, min: 0.0000,	mean: 0.0103,	max: 0.0188
iter: 300, min: 0.0000,	mean: 0.0085,	max: 0.0155
iter: 350, min: 0.0000,	mean: 0.0073,	max: 0.0134
iter: 400, min: 0.0000,	mean: 0.0064,	max: 0.0118
iter: 450, min: 0.0000,	mean: 0.0057,	max: 0.0104
iter: 500, min: 0.0000,	mean: 0.0050,	max: 0.0093
iter: 550, min: 0.0000,	mean: 0.0045,	max: 0.0085
iter: 600, min: 0.0000,	mean: 0.0041,	max: 0.0076
iter: 650, min: 0.0000,	mean: 0.0037,	max: 0.0069
iter: 700, min: 0.0000,	mean: 0.0034,	max: 0.0063
iter: 750, min: 0.0000,	mean: 0.0032,	max: 0.0060
iter: 800, min: 0.0000,	mean: 0.0030,	max: 0.0055
iter: 850, min: 0.0000,	mean: 0.0028,	max: 0.0052
iter: 900, min: 0.0000,	mean: 0.0026,	max: 0.0049
iter: 950, min: 0.0000,	mean: 0.0025,	max: 0.0

(array([[2.99929961, 0.50018529],
        [1.15011312, 0.6718162 ]]), 3.04997276610045e-06)

#### optimum = 0 at (3, 0.5)

### Rosenbrock Function
##### $f(x) = \sum_{i=1}^{N-1}[100 * (x_{i}^2 - x_{i+1})^2 + (1 - x_i)^2]$

In [9]:
def rosenbrock(population):
    return np.array([(100*(ind[:-1]**2 - ind[1:])**2 + (ind[:-1] - 1)**2).sum() 
                     for ind in population])

In [10]:
dims = 2

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-5, 10), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='roulette', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=rosenbrock, max_iters=1000)

In [11]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 6.2371,	mean: 184876.6002,	max: 616320.2078
iter: 50, min: 0.2617,	mean: 13.4520,	max: 21.8248
iter: 100, min: 0.0855,	mean: 8.0558,	max: 12.3407
iter: 150, min: 0.0810,	mean: 6.3113,	max: 9.4610
iter: 200, min: 0.0810,	mean: 5.2082,	max: 7.8175
iter: 250, min: 0.0810,	mean: 4.5080,	max: 6.7294
iter: 300, min: 0.0810,	mean: 4.0104,	max: 5.8997
iter: 350, min: 0.0810,	mean: 3.6387,	max: 5.3225
iter: 400, min: 0.0810,	mean: 3.2859,	max: 4.8833
iter: 450, min: 0.0810,	mean: 2.9933,	max: 4.5362
iter: 500, min: 0.0810,	mean: 2.7231,	max: 4.2022
iter: 550, min: 0.0810,	mean: 2.4945,	max: 3.9471
iter: 600, min: 0.0810,	mean: 2.3213,	max: 3.7093
iter: 650, min: 0.0810,	mean: 2.1280,	max: 3.4717
iter: 700, min: 0.0810,	mean: 1.9037,	max: 3.2065
iter: 750, min: 0.0810,	mean: 1.7676,	max: 2.9586
iter: 800, min: 0.0810,	mean: 1.6281,	max: 2.7300
iter: 850, min: 0.0699,	mean: 1.4987,	max: 2.5246
iter: 900, min: 0.0699,	mean: 1.3947,	max: 2.3825
iter: 950, min: 0.0699,	mean: 1.2977,	ma

(array([[0.83269058, 0.79986791],
        [0.68915609, 0.64058096]]), 0.06988681668233997)

#### optimum = 0 at (1, ..., 1)

### Rastrigin Function
##### $f(x) = 10*N + \sum_{i=1}^N[{x_i^2 - 10*\cos(2 \pi * x_i)}]$

In [12]:
def rastrigin(population):
    dims = population.shape[-1]
    return 10*dims + np.array([(ind[0]**2 - 10 * np.cos(2*np.pi * ind[0])).sum() 
                               for ind in population])

In [13]:
dims = 2

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-5.12, 5.12), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='roulette', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=rastrigin, max_iters=1000)

In [14]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 1.1145,	mean: 30.2567,	max: 44.2262
iter: 50, min: 0.0880,	mean: 4.8230,	max: 7.0688
iter: 100, min: 0.0824,	mean: 3.1913,	max: 4.8544
iter: 150, min: 0.0321,	mean: 2.3980,	max: 3.7212
iter: 200, min: 0.0321,	mean: 2.0426,	max: 3.0209
iter: 250, min: 0.0321,	mean: 1.8334,	max: 2.6141
iter: 300, min: 0.0321,	mean: 1.6904,	max: 2.3941
iter: 350, min: 0.0264,	mean: 1.5810,	max: 2.2277
iter: 400, min: 0.0264,	mean: 1.4945,	max: 2.1071
iter: 450, min: 0.0122,	mean: 1.4131,	max: 2.0194
iter: 500, min: 0.0122,	mean: 1.3461,	max: 1.9152
iter: 550, min: 0.0122,	mean: 1.2889,	max: 1.8018
iter: 600, min: 0.0122,	mean: 1.2400,	max: 1.7010
iter: 650, min: 0.0122,	mean: 1.2046,	max: 1.6464
iter: 700, min: 0.0122,	mean: 1.1797,	max: 1.6014
iter: 750, min: 0.0122,	mean: 1.1527,	max: 1.5550
iter: 800, min: 0.0019,	mean: 1.1203,	max: 1.4987
iter: 850, min: 0.0019,	mean: 1.0936,	max: 1.4610
iter: 900, min: 0.0019,	mean: 1.0711,	max: 1.4311
iter: 950, min: 0.0019,	mean: 1.0482,	max: 1.3994


(array([[-0.00188671, -0.00246884],
        [ 1.28922154,  1.19428674]]), 0.0019154085112944585)

#### optimum = 0 at (0, ..., 0)

### Griewank Function
##### $f(x) = 1 + \frac{1}{4000}\sum_{i=1}^Nx_i^2 - \prod_{i=1}^N\cos(\frac{x_i}{\sqrt i})$

In [15]:
def griewank(population):
    dims = population.shape[-1]
    return 1 + 1/4000*np.array([(ind[0]**2).sum() for ind in population]) -\
        np.prod([np.cos(ind[0] / np.sqrt([i+1 for i in range(dims)])) for ind in population])

In [16]:
dims = 2

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-600, 600), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='roulette', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=griewank, max_iters=1000)

In [17]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 1.0108,	mean: 46.3470,	max: 84.5043
iter: 50, min: 1.0095,	mean: 1.0127,	max: 1.0142
iter: 100, min: 1.0087,	mean: 1.0094,	max: 1.0096
iter: 150, min: 1.0086,	mean: 1.0090,	max: 1.0091
iter: 200, min: 1.0086,	mean: 1.0089,	max: 1.0090
iter: 250, min: 1.0086,	mean: 1.0088,	max: 1.0089
iter: 300, min: 1.0085,	mean: 1.0088,	max: 1.0088
iter: 350, min: 1.0085,	mean: 1.0087,	max: 1.0088
iter: 400, min: 1.0085,	mean: 1.0087,	max: 1.0088
iter: 450, min: 1.0085,	mean: 1.0087,	max: 1.0088
iter: 500, min: 1.0085,	mean: 1.0087,	max: 1.0087
iter: 550, min: 1.0085,	mean: 1.0087,	max: 1.0087
iter: 600, min: 1.0085,	mean: 1.0087,	max: 1.0087
iter: 650, min: 1.0085,	mean: 1.0087,	max: 1.0087
iter: 700, min: 1.0085,	mean: 1.0087,	max: 1.0087
iter: 750, min: 1.0085,	mean: 1.0087,	max: 1.0087
iter: 800, min: 1.0085,	mean: 1.0087,	max: 1.0087
iter: 850, min: 1.0085,	mean: 1.0086,	max: 1.0087
iter: 900, min: 1.0085,	mean: 1.0086,	max: 1.0087
iter: 950, min: 1.0085,	mean: 1.0086,	max: 1.0087


(array([[0.17184363, 5.83951438],
        [1.05460609, 0.56636463]]), 1.0085323646026558)

#### optimum = 0 at (0, ..., 0)