In [1]:
import numpy as np
from ES import ES

# Zadanie 1.
a) Zaimplementuj omawiane na wykładzie strategie ewolucyjne ES(μ + λ) i ES(μ, λ).
Wskazówka: Algorytmy można zaimplementować w dowolnym języku programowania, ale ze względu na wygodę i wydajność obliczeń (głównie związanych z operacjami wektorowo-macierzowymi i losowaniem danych z rozkładu normalnego) radziłbym używać środowisk dedykowanych do obliczeń wektorowo- macierzowych, m.in. Matlab, Octave lub Python z biblioteką Numpy.

b) Zapoznaj się z popularnymi benchmarkami dla optymalizacji globalnej (http://www-optima.amp.i.kyoto-u.ac.jp/member/student/hedar/Hedar_files/TestGO.htm), zarówno problemami optymalizacji bez ograniczeń jak i z ograniczeniami. Wybierz 5 benchmarków bez ograniczeń i użyj zaimplementowanych algorytmów do ich rozwiązywania (wśród wybranych benchmarków powinna znaleźć się co najmniej jedna z następujących funkcji: Griewank Function, Rastrigin Function, Schwefel Function). Dokładnie przeanalizuj działanie algorytmu i otrzymane wyniki. Sprawdź różne ustawienia algorytmu.

### Sum squares function
##### $f(x) = \sum_{i=1}^n{ix_i^2}$

In [2]:
def sum_squares(population):
    return np.array(list(map(lambda ind: ind[0]**2 * np.arange(1, len(ind[0])+1), 
                             population))).sum(axis=1)

In [3]:
dims = 3

lr = 0.1
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-10, 10), dims=3, population_size=1000, offspring_size=500, 
        parent_choice_method='random', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=sum_squares, max_iters=1000)

In [4]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 1.9113,	mean: 141.1925,	max: 255.3585
iter: 50, min: 0.0158,	mean: 0.8605,	max: 1.3963
iter: 100, min: 0.0158,	mean: 0.5286,	max: 0.8244
iter: 150, min: 0.0048,	mean: 0.4077,	max: 0.6488
iter: 200, min: 0.0048,	mean: 0.3411,	max: 0.5341
iter: 250, min: 0.0048,	mean: 0.2986,	max: 0.4658
iter: 300, min: 0.0048,	mean: 0.2706,	max: 0.4189
iter: 350, min: 0.0048,	mean: 0.2487,	max: 0.3816
iter: 400, min: 0.0048,	mean: 0.2325,	max: 0.3575
iter: 450, min: 0.0048,	mean: 0.2192,	max: 0.3349
iter: 500, min: 0.0048,	mean: 0.2065,	max: 0.3163
iter: 550, min: 0.0048,	mean: 0.1950,	max: 0.3017
iter: 600, min: 0.0048,	mean: 0.1873,	max: 0.2909
iter: 650, min: 0.0048,	mean: 0.1783,	max: 0.2774
iter: 700, min: 0.0048,	mean: 0.1707,	max: 0.2640
iter: 750, min: 0.0048,	mean: 0.1626,	max: 0.2517
iter: 800, min: 0.0048,	mean: 0.1567,	max: 0.2429
iter: 850, min: 0.0048,	mean: 0.1515,	max: 0.2324
iter: 900, min: 0.0048,	mean: 0.1470,	max: 0.2236
iter: 950, min: 0.0048,	mean: 0.1424,	max: 0.2157

(array([[-0.06806071,  0.00636301,  0.00662403],
        [ 1.11612954,  0.78113462,  1.21401583]]), 0.004844869583364683)

#### optimum = 0 at (0, ..., 0)

### Beale Function
##### $f(x) = (1.5 - x_1 + x_1*x_2)^2 + (2.25 - x_1 + x_1*x_2^2)^2 + (2.625 - x_1 + x_1*x_2^3)^2$

In [5]:
def beale(population):
    return np.array([(1.5 - ind[0][0] + ind[0][0]*ind[0][1])**2 + \
                     (2.25 - ind[0][0] + ind[0][0]*ind[0][1]**2)**2 + \
                     (2.625 - ind[0][0] + ind[0][0]*ind[0][1]**3)**2
                     for ind in population])

In [6]:
dims = 2

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-4.5, 4.5), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='random', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=beale, max_iters=1000)

In [7]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 0.0158,	mean: 362.9922,	max: 2546.0265
iter: 50, min: 0.0001,	mean: 0.0413,	max: 0.0763
iter: 100, min: 0.0000,	mean: 0.0217,	max: 0.0392
iter: 150, min: 0.0000,	mean: 0.0143,	max: 0.0257
iter: 200, min: 0.0000,	mean: 0.0110,	max: 0.0202
iter: 250, min: 0.0000,	mean: 0.0086,	max: 0.0158
iter: 300, min: 0.0000,	mean: 0.0072,	max: 0.0130
iter: 350, min: 0.0000,	mean: 0.0063,	max: 0.0114
iter: 400, min: 0.0000,	mean: 0.0057,	max: 0.0102
iter: 450, min: 0.0000,	mean: 0.0050,	max: 0.0090
iter: 500, min: 0.0000,	mean: 0.0045,	max: 0.0081
iter: 550, min: 0.0000,	mean: 0.0041,	max: 0.0074
iter: 600, min: 0.0000,	mean: 0.0038,	max: 0.0068
iter: 650, min: 0.0000,	mean: 0.0035,	max: 0.0064
iter: 700, min: 0.0000,	mean: 0.0033,	max: 0.0059
iter: 750, min: 0.0000,	mean: 0.0031,	max: 0.0055
iter: 800, min: 0.0000,	mean: 0.0028,	max: 0.0051
iter: 850, min: 0.0000,	mean: 0.0027,	max: 0.0049
iter: 900, min: 0.0000,	mean: 0.0025,	max: 0.0046
iter: 950, min: 0.0000,	mean: 0.0024,	max: 0.004

(array([[3.00246919, 0.50058646],
        [0.72372268, 0.61441832]]), 9.879019544200851e-07)

#### optimum = 0 at (3, 0.5)

### Rosenbrock Function
##### $f(x) = \sum_{i=1}^{N-1}[100 * (x_{i}^2 - x_{i+1})^2 + (1 - x_i)^2]$

In [8]:
def rosenbrock(population):
    return np.array([(100*(ind[:-1]**2 - ind[1:])**2 + (ind[:-1] - 1)**2).sum() 
                     for ind in population])

In [9]:
dims = 5

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-5, 10), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='random', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=rosenbrock, max_iters=1000)

In [10]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 786.5203,	mean: 377375.4883,	max: 880433.2480
iter: 50, min: 22.1357,	mean: 169.0428,	max: 235.0711
iter: 100, min: 22.1357,	mean: 135.1299,	max: 183.1101
iter: 150, min: 21.5592,	mean: 121.6782,	max: 164.3747
iter: 200, min: 19.3808,	mean: 112.3789,	max: 151.7747
iter: 250, min: 19.3808,	mean: 106.2888,	max: 143.0695
iter: 300, min: 19.3808,	mean: 101.4564,	max: 136.7199
iter: 350, min: 19.3808,	mean: 97.1006,	max: 130.8402
iter: 400, min: 19.3808,	mean: 94.1730,	max: 125.6281
iter: 450, min: 19.3808,	mean: 91.3468,	max: 121.4198
iter: 500, min: 19.3808,	mean: 89.2245,	max: 118.4501
iter: 550, min: 19.3808,	mean: 87.4577,	max: 116.1967
iter: 600, min: 10.0937,	mean: 85.3959,	max: 113.0699
iter: 650, min: 10.0937,	mean: 83.8917,	max: 110.7672
iter: 700, min: 10.0937,	mean: 82.7369,	max: 108.8860
iter: 750, min: 10.0937,	mean: 80.9020,	max: 106.1784
iter: 800, min: 10.0937,	mean: 79.7114,	max: 104.3869
iter: 850, min: 10.0937,	mean: 78.7498,	max: 103.2109
iter: 900, min: 1

(array([[ 1.0422597 , -0.82514416,  1.10067054,  1.29108493,  0.95218021],
        [ 0.99121122,  0.70242561,  1.0264286 ,  1.51683592,  0.8875134 ]]),
 10.093654297470774)

#### optimum = 0 at (1, ..., 1)

### Rastrigin Function
##### $f(x) = 10*N + \sum_{i=1}^N{x_i^2 - 10*\cos(2 \pi * x_i)}$

In [11]:
def rastrigin(population):
    dims = population.shape[-1]
    return 10*dims + np.array([(ind[0]**2 - 10 * np.cos(2*np.pi * ind[0])).sum() 
                               for ind in population])

In [12]:
dims = 5

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-5.12, 5.12), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='random', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=rastrigin, max_iters=1000)

In [13]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 30.0286,	mean: 80.2247,	max: 102.5705
iter: 50, min: 9.1147,	mean: 31.8152,	max: 38.2822
iter: 100, min: 9.1147,	mean: 26.7606,	max: 32.3358
iter: 150, min: 9.1147,	mean: 24.7079,	max: 29.5018
iter: 200, min: 9.1147,	mean: 23.1439,	max: 27.8368
iter: 250, min: 6.8540,	mean: 22.0624,	max: 26.7004
iter: 300, min: 6.8540,	mean: 21.3863,	max: 25.6773
iter: 350, min: 6.8540,	mean: 20.7584,	max: 24.9389
iter: 400, min: 6.8540,	mean: 20.2571,	max: 24.2962
iter: 450, min: 6.8540,	mean: 19.8797,	max: 23.8096
iter: 500, min: 6.8540,	mean: 19.4873,	max: 23.4027
iter: 550, min: 6.8540,	mean: 19.1025,	max: 22.9551
iter: 600, min: 6.8540,	mean: 18.7825,	max: 22.5031
iter: 650, min: 6.8540,	mean: 18.5062,	max: 22.1189
iter: 700, min: 6.8540,	mean: 18.2682,	max: 21.7995
iter: 750, min: 6.8540,	mean: 18.1024,	max: 21.5758
iter: 800, min: 6.8540,	mean: 17.8676,	max: 21.2598
iter: 850, min: 6.8540,	mean: 17.6685,	max: 21.0778
iter: 900, min: 6.8540,	mean: 17.4856,	max: 20.8674
iter: 950, mi

(array([[ 0.96845795, -0.93005058,  1.02664718,  0.04356007,  0.1107453 ],
        [ 0.81315838,  0.6282441 ,  1.04531596,  1.08050511,  1.11374678]]),
 6.854043981799556)

#### optimum = 0 at (0, ..., 0)

### Griewank Function
##### $f(x) = 1 + \frac{1}{4000}\sum_{i=1}^Nx_i^2 - \prod_{i=1}^N\cos(\frac{x_i}{\sqrt i})$

In [14]:
def griewank(population):
    dims = population.shape[-1]
    return 1 + 1/4000*np.array([(ind[0]**2).sum() for ind in population]) -\
        np.prod([np.cos(ind[0] / np.sqrt([i+1 for i in range(dims)])) for ind in population])

In [15]:
dims = 2

lr = 0.01
tau0, tau = lr/np.sqrt(2 * np.sqrt(dims)), lr/np.sqrt(2*dims)

es = ES(domain=(-600, 600), dims=dims, population_size=1000, offspring_size=500, 
        parent_choice_method='random', replacement_method='mulambda', tau=tau, 
        tau0=tau0, cost_func=griewank, max_iters=1000)

In [16]:
es.run(verbose=True, with_tqdm=False)

iter: 0, min: 1.1771,	mean: 38.9978,	max: 76.7079
iter: 50, min: 1.1002,	mean: 1.1126,	max: 1.1160
iter: 100, min: 1.0472,	mean: 1.0540,	max: 1.0558
iter: 150, min: 1.0302,	mean: 1.0355,	max: 1.0367
iter: 200, min: 1.0255,	mean: 1.0290,	max: 1.0297
iter: 250, min: 1.0233,	mean: 1.0256,	max: 1.0261
iter: 300, min: 1.0221,	mean: 1.0240,	max: 1.0245
iter: 350, min: 1.0221,	mean: 1.0232,	max: 1.0236
iter: 400, min: 1.0215,	mean: 1.0227,	max: 1.0230
iter: 450, min: 1.0212,	mean: 1.0223,	max: 1.0226
iter: 500, min: 1.0209,	mean: 1.0220,	max: 1.0222
iter: 550, min: 1.0209,	mean: 1.0217,	max: 1.0219
iter: 600, min: 1.0209,	mean: 1.0215,	max: 1.0217
iter: 650, min: 1.0209,	mean: 1.0214,	max: 1.0215
iter: 700, min: 1.0208,	mean: 1.0213,	max: 1.0214
iter: 750, min: 1.0208,	mean: 1.0212,	max: 1.0213
iter: 800, min: 1.0207,	mean: 1.0211,	max: 1.0213
iter: 850, min: 1.0207,	mean: 1.0211,	max: 1.0212
iter: 900, min: 1.0207,	mean: 1.0211,	max: 1.0212
iter: 950, min: 1.0207,	mean: 1.0210,	max: 1.0211


(array([[ 9.10450568e+00, -3.33100927e-03],
        [ 1.65751397e+00,  8.05088380e-01]]), 1.0207230087054966)

#### optimum = 0 at (0, ..., 0)